# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.28.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.28.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/maxrt/CLionProjects/xcfg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/maxrt/CLionProjects/xcfg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.28.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.28.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maxrt/CLionProjects/xcfg/CMakeFiles /Users/maxrt/CLionProjects/xcfg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maxrt/CLionProjects/xcfg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xcfg

# Build rule for target.
xcfg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xcfg
.PHONY : xcfg

# fast build rule for target.
xcfg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/build
.PHONY : xcfg/fast

#=============================================================================
# Target rules for targets named xcfg_example

# Build rule for target.
xcfg_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xcfg_example
.PHONY : xcfg_example

# fast build rule for target.
xcfg_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg_example.dir/build.make CMakeFiles/xcfg_example.dir/build
.PHONY : xcfg_example/fast

src/example/example.o: src/example/example.cc.o
.PHONY : src/example/example.o

# target to build an object file
src/example/example.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/example/example.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg_example.dir/build.make CMakeFiles/xcfg_example.dir/src/example/example.cc.o
.PHONY : src/example/example.cc.o

src/example/example.i: src/example/example.cc.i
.PHONY : src/example/example.i

# target to preprocess a source file
src/example/example.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/example/example.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg_example.dir/build.make CMakeFiles/xcfg_example.dir/src/example/example.cc.i
.PHONY : src/example/example.cc.i

src/example/example.s: src/example/example.cc.s
.PHONY : src/example/example.s

# target to generate assembly for a file
src/example/example.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/example/example.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg_example.dir/build.make CMakeFiles/xcfg_example.dir/src/example/example.cc.s
.PHONY : src/example/example.cc.s

src/xfg/data.o: src/xfg/data.cc.o
.PHONY : src/xfg/data.o

# target to build an object file
src/xfg/data.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/data.cc.o
.PHONY : src/xfg/data.cc.o

src/xfg/data.i: src/xfg/data.cc.i
.PHONY : src/xfg/data.i

# target to preprocess a source file
src/xfg/data.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/data.cc.i
.PHONY : src/xfg/data.cc.i

src/xfg/data.s: src/xfg/data.cc.s
.PHONY : src/xfg/data.s

# target to generate assembly for a file
src/xfg/data.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/data.cc.s
.PHONY : src/xfg/data.cc.s

src/xfg/exceptions.o: src/xfg/exceptions.cc.o
.PHONY : src/xfg/exceptions.o

# target to build an object file
src/xfg/exceptions.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/exceptions.cc.o
.PHONY : src/xfg/exceptions.cc.o

src/xfg/exceptions.i: src/xfg/exceptions.cc.i
.PHONY : src/xfg/exceptions.i

# target to preprocess a source file
src/xfg/exceptions.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/exceptions.cc.i
.PHONY : src/xfg/exceptions.cc.i

src/xfg/exceptions.s: src/xfg/exceptions.cc.s
.PHONY : src/xfg/exceptions.s

# target to generate assembly for a file
src/xfg/exceptions.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/exceptions.cc.s
.PHONY : src/xfg/exceptions.cc.s

src/xfg/parser.o: src/xfg/parser.cc.o
.PHONY : src/xfg/parser.o

# target to build an object file
src/xfg/parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/parser.cc.o
.PHONY : src/xfg/parser.cc.o

src/xfg/parser.i: src/xfg/parser.cc.i
.PHONY : src/xfg/parser.i

# target to preprocess a source file
src/xfg/parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/parser.cc.i
.PHONY : src/xfg/parser.cc.i

src/xfg/parser.s: src/xfg/parser.cc.s
.PHONY : src/xfg/parser.s

# target to generate assembly for a file
src/xfg/parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/parser.cc.s
.PHONY : src/xfg/parser.cc.s

src/xfg/processor.o: src/xfg/processor.cc.o
.PHONY : src/xfg/processor.o

# target to build an object file
src/xfg/processor.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/processor.cc.o
.PHONY : src/xfg/processor.cc.o

src/xfg/processor.i: src/xfg/processor.cc.i
.PHONY : src/xfg/processor.i

# target to preprocess a source file
src/xfg/processor.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/processor.cc.i
.PHONY : src/xfg/processor.cc.i

src/xfg/processor.s: src/xfg/processor.cc.s
.PHONY : src/xfg/processor.s

# target to generate assembly for a file
src/xfg/processor.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/processor.cc.s
.PHONY : src/xfg/processor.cc.s

src/xfg/tokenizer.o: src/xfg/tokenizer.cc.o
.PHONY : src/xfg/tokenizer.o

# target to build an object file
src/xfg/tokenizer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/tokenizer.cc.o
.PHONY : src/xfg/tokenizer.cc.o

src/xfg/tokenizer.i: src/xfg/tokenizer.cc.i
.PHONY : src/xfg/tokenizer.i

# target to preprocess a source file
src/xfg/tokenizer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/tokenizer.cc.i
.PHONY : src/xfg/tokenizer.cc.i

src/xfg/tokenizer.s: src/xfg/tokenizer.cc.s
.PHONY : src/xfg/tokenizer.s

# target to generate assembly for a file
src/xfg/tokenizer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/tokenizer.cc.s
.PHONY : src/xfg/tokenizer.cc.s

src/xfg/util/path.o: src/xfg/util/path.cc.o
.PHONY : src/xfg/util/path.o

# target to build an object file
src/xfg/util/path.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/util/path.cc.o
.PHONY : src/xfg/util/path.cc.o

src/xfg/util/path.i: src/xfg/util/path.cc.i
.PHONY : src/xfg/util/path.i

# target to preprocess a source file
src/xfg/util/path.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/util/path.cc.i
.PHONY : src/xfg/util/path.cc.i

src/xfg/util/path.s: src/xfg/util/path.cc.s
.PHONY : src/xfg/util/path.s

# target to generate assembly for a file
src/xfg/util/path.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/util/path.cc.s
.PHONY : src/xfg/util/path.cc.s

src/xfg/util/string.o: src/xfg/util/string.cc.o
.PHONY : src/xfg/util/string.o

# target to build an object file
src/xfg/util/string.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/util/string.cc.o
.PHONY : src/xfg/util/string.cc.o

src/xfg/util/string.i: src/xfg/util/string.cc.i
.PHONY : src/xfg/util/string.i

# target to preprocess a source file
src/xfg/util/string.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/util/string.cc.i
.PHONY : src/xfg/util/string.cc.i

src/xfg/util/string.s: src/xfg/util/string.cc.s
.PHONY : src/xfg/util/string.s

# target to generate assembly for a file
src/xfg/util/string.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/util/string.cc.s
.PHONY : src/xfg/util/string.cc.s

src/xfg/value.o: src/xfg/value.cc.o
.PHONY : src/xfg/value.o

# target to build an object file
src/xfg/value.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/value.cc.o
.PHONY : src/xfg/value.cc.o

src/xfg/value.i: src/xfg/value.cc.i
.PHONY : src/xfg/value.i

# target to preprocess a source file
src/xfg/value.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/value.cc.i
.PHONY : src/xfg/value.cc.i

src/xfg/value.s: src/xfg/value.cc.s
.PHONY : src/xfg/value.s

# target to generate assembly for a file
src/xfg/value.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/value.cc.s
.PHONY : src/xfg/value.cc.s

src/xfg/xcfg.o: src/xfg/xcfg.cc.o
.PHONY : src/xfg/xcfg.o

# target to build an object file
src/xfg/xcfg.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/xcfg.cc.o
.PHONY : src/xfg/xcfg.cc.o

src/xfg/xcfg.i: src/xfg/xcfg.cc.i
.PHONY : src/xfg/xcfg.i

# target to preprocess a source file
src/xfg/xcfg.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/xcfg.cc.i
.PHONY : src/xfg/xcfg.cc.i

src/xfg/xcfg.s: src/xfg/xcfg.cc.s
.PHONY : src/xfg/xcfg.s

# target to generate assembly for a file
src/xfg/xcfg.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcfg.dir/build.make CMakeFiles/xcfg.dir/src/xfg/xcfg.cc.s
.PHONY : src/xfg/xcfg.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xcfg"
	@echo "... xcfg_example"
	@echo "... src/example/example.o"
	@echo "... src/example/example.i"
	@echo "... src/example/example.s"
	@echo "... src/xfg/data.o"
	@echo "... src/xfg/data.i"
	@echo "... src/xfg/data.s"
	@echo "... src/xfg/exceptions.o"
	@echo "... src/xfg/exceptions.i"
	@echo "... src/xfg/exceptions.s"
	@echo "... src/xfg/parser.o"
	@echo "... src/xfg/parser.i"
	@echo "... src/xfg/parser.s"
	@echo "... src/xfg/processor.o"
	@echo "... src/xfg/processor.i"
	@echo "... src/xfg/processor.s"
	@echo "... src/xfg/tokenizer.o"
	@echo "... src/xfg/tokenizer.i"
	@echo "... src/xfg/tokenizer.s"
	@echo "... src/xfg/util/path.o"
	@echo "... src/xfg/util/path.i"
	@echo "... src/xfg/util/path.s"
	@echo "... src/xfg/util/string.o"
	@echo "... src/xfg/util/string.i"
	@echo "... src/xfg/util/string.s"
	@echo "... src/xfg/value.o"
	@echo "... src/xfg/value.i"
	@echo "... src/xfg/value.s"
	@echo "... src/xfg/xcfg.o"
	@echo "... src/xfg/xcfg.i"
	@echo "... src/xfg/xcfg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

